# Section 1 - This is the part that defines the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  labels:
    tier: mailhog

# Section 2 - This is the Replica set layer controlled by the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: mailhog

# Section 3 - This is the Pod section controlled by the deployment and selected by the replica set in section 2.
  template:
    metadata:
      labels:
        tier: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - containerPort: 8025

