apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: "cert-manager"
  name: "letsencrypt-production"
spec:
  acme:
    # The ACME server URL
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "dare@darey.io"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "letsencrypt-production"
    solvers:
    - selector:
        dnsZones:
          - "svc.steghub.com"
      dns01:
        route53:
          region: "eu-west-2"
          hostedZoneID: "Z07778562K055K5DQB0TI"