  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: jenkins
  spec:
    ingressClassName: nginx
    rules:
      - host: jenkins.tooling.devops-masterclass.link
        http:
          paths:
            - backend:
                service:
                  name: jenkins-release
                  port:
                    number: 8080
              path: /
              pathType: Prefix
#     This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.jenkins.tooling.devops-masterclass.link
          secretName: wildcard.devops-masterclass.link

# If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:
