  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    name: prometheus
  spec:
    ingressClassName: nginx
    rules:
      - host: www.prometheus.tooling.devops-masterclass.link
        http:
          paths:
            - backend:
                service:
                  name: prometheus-server
                  port:
                    number: 9090
              path: /
              pathType: Prefix
      - host: prometheus.tooling.devops-masterclass.link
        http:
          paths:
            - backend:
                service:
                  name: prometheus-server
                  port:
                    number: 9090
              path: /
              pathType: Prefix
#     This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.prometheus.tooling.devops-masterclass.link
            - prometheus.tooling.devops-masterclass.link
          secretName: prometheus.tooling.devops-masterclass.link
# If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:
