  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: jenkins
  spec:
    ingressClassName: nginx
    rules:
      - host: www.jenkins.tooling.devops-masterclass.link
        http:
          paths:
            - backend:
                service:
                  name: jenkins
                  port:
                    number: 8080
              path: /
              pathType: Prefix
      - host: jenkins.tooling.devops-masterclass.link
        http:
          paths:
            - backend:
                service:
                  name: jenkins
                  port:
                    number: 8080
              path: /
              pathType: Prefix