
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  grafana-https.conf: |
    server {
      listen 80;
      server_name  grafana;

      ssl_certificate           /etc/nginx/tls/tls.crt;
      ssl_certificate_key       /etc/nginx/tls/tls.key;

      ssl on;
      ssl_session_cache  builtin:1000  shared:SSL:10m;
      ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
      ssl_prefer_server_ciphers on;

      access_log /var/log/nginx/reverse-access.log;
      error_log /var/log/nginx/reverse-error.log;

      location / {
      proxy_pass http://grafana;
      }
    }
