apiVersion: v1
kind: Pod
metadata:
  name: tooling-pod
  annotations:
    vault.harshicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "tooling-app"
    vault.harshicorp.com/agent-inject-secret-mysqlPassword: "kv2/data/tooling/dev/MYSQL_PASS"
    vault.hashicorp.com/agent-inject-template-helloworld: |
      {{`{{- with secret "kv2/data/tooling/dev/MYSQL_PASS" -}}
      export MYSQL_PASS={{ .Data.data.MYSQL_PASS }}
      {{- end }}`}}
  labels:
    app.kubernetes.io/instance: tooling
    app.kubernetes.io/name: tooling
spec:
  containers:
  - env:
          - name: MYSQL_IP
            value: my-mysql
          - name: MYSQL_USER
            value: tooling
          - name: MYSQL_DBNAME
            value: toolingdb
    image: dareyregistry/tooling:1.0.0
    imagePullPolicy: IfNotPresent
    name: tooling
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
