databaseUpgradeReady: true
artifactory:
  replicaCount: 3
  joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
  masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  persistence:
    enabled: false
  replicator:
    name: replicator
    enabled: true
    pdn:
      tracker:
        enabled: false
    ingress:
      name:
      hosts: []
      className: "testclass1"
    trackerIngress:
      enabled: true
      className: "testclass2"
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "6Gi"
      cpu: "4"

postgresql:
  postgresqlPassword: password
  postgresqlExtendedConf:
    maxConnections: 100
  persistence:
    enabled: false

rbac:
  create: true
serviceAccount:
  create: true
  automountServiceAccountToken: true

ingress:
  enabled: true
  className: "testclass"
  hosts:
    - demonow.xyz
nginx:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
