---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  name: nginx-ingress
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress-controller
      app.kubernetes.io/instance: nginx-ingress
      app.kubernetes.io/component: metrics
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: nginx-ingress-controller-9.1.3
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - path: /metrics
    targetPort: 9913
    interval: 5s



